### PR TITLE
Support OES_depth_texture through MetalANGLE (commit 30426abb)

### PR DESCRIPTION
**Pull request by kakashidinho**
There is another tweak though, need to enable MOBILE_GRAPHICS mode in `Source/Urho3D/Graphics/GraphicsDefs.h` when using ANGLE even if compiling for Mac since Urho3D shadow mapping shader by default only expects one shadow map in GLSL ES mode. This is the default code in `Lighting.glsl`:
```
#if !defined(GL_ES) || defined(WEBGL)
float GetDirShadow(const vec4 iShadowPos[NUMCASCADES], float depth)
{
    vec4 shadowPos;

    if (depth < cShadowSplits.x)
        shadowPos = iShadowPos[0];
    else if (depth < cShadowSplits.y)
        shadowPos = iShadowPos[1];
    else if (depth < cShadowSplits.z)
        shadowPos = iShadowPos[2];
    else
        shadowPos = iShadowPos[3];
        
    return GetDirShadowFade(GetShadow(shadowPos), depth);
}
#else
float GetDirShadow(const highp vec4 iShadowPos[NUMCASCADES], float depth)
{
    return GetDirShadowFade(GetShadow(iShadowPos[0]), depth);
}
#endif
```
If DESKTOP_GRAPHICS is turned on, the app code will create multiple shadow maps (to increase shadow distance), thus the GLSL ES shader wouldn't work correctly. This is mismatch in handling number of shadow maps between app code and GLSL code.
I think we need to inform devs if they want to use ANGLE on Mac in future. They need to support multiple shadow maps in shader if it is GLSL ES running on desktop.

### CODE REVIEW

**Comment by kakashidinho** [comment]
Nvm, I have changed Urho3D code to support multiple shadowmaps for GLES running on desktop

**Comment by elix22** [comment]
Awesome , thanks

**Comment by elix22** [comment]
Sample 23_Water  is broken , I think it used to work.
However it was not broken by this P.R. , I think it broke by the previous P.R.

**Comment by kakashidinho** [comment]
Is it the problem of only half the screen is rendered? iOS and AMD macbook run fine for me. Only Intel gpu seems to have problems, not sure this is intel bug or urho3d or angle bug.

**Comment by elix22** [comment]
Screen Shot 2019-11-16 at 21 18 16

**Comment by elix22** [comment]
If I am not mistaken , it used to work  with your previous commits

**Comment by elix22** [comment]
Yes on iOS it works fine , on my MBP 13`(Intel chip) it's broken

**Comment by kakashidinho** [comment]
OK, looks like I found out why. 90% it was a bug in Metal capture lib from Intel. If you disable
GPU frame capture option in the scheme settings, it will work fine:

Screenshot 2019-11-17 at 3 51 20 AM

**Comment by kakashidinho** [comment]
I set a data watchpoint, the watchpoint hit some point in the capture lib from intel, the code at this point somehow overwrote the metal vertex buffer's data created by Urho3d for rendering fullscreen quad, thus the fullscreen quad became half screen only.

**Comment by elix22** [comment]
Yes , disabling GPU Frame Capture , fixed it.
You might have found an an Intel bug  :)

**Comment by elix22** [comment]
@kakashidinho
F.Y.I
I created a new branch https://github.com/elix22/Urho3D/tree/dev
based upon latest Urho3D master .

It contains your metal-backend 
- Shadows are working fine now on iOS devices .
- the entire screen is utilized on  iOS devices .
- multi-touch is working on iOS .
- some Urho3D fixes .

Please note that Bluetooth framework is included now in iOS/macOS, 
So you will see some popup on your screen (on iOS device)  , you can decline it.

**Comment by kakashidinho** [comment]
OK, thanks.
FYI, I have been fixed several critical bugs in metalangle since this pull request.
Also, MRT is ready, however the PBR is still not working correctly, probably due to something else not related to MRT, probably the way the #ifdef is handled in Urho3d w.r.t GLES

**Comment by elix22** [comment]
Thanks
I merged your latest fixes , part of a new branch based upon Urho3D latest fixes
https://github.com/elix22/Urho3D/tree/dev-metal-backend

I added also a new sample 69_MaterialEffects  ,I plan to add more samples

**Pull request merged**
