### PR TITLE
Merge with latest code from MetalANGLE to support true npot textures

### PR DESCRIPTION
**Pull request by kakashidinho**
2d platformer sample apps should display everything correctly now.

### CODE REVIEW

**Comment by elix22** [comment]
Works like a charm , amazing work .
It's amazing that you implemented this entire feature (metal backend) by yourself .

Some general suggestions  about some missing implementations 
1. Missing shadows (requires 'GL_OES_depth_texture' support) , you can try 06_SkeletalAnimation (with OpenGL/ES backend)  to verify shadows 
2. 35_SignedDistanceFieldText - no text

Once again thanks for your amazing contribution .

**Comment by kakashidinho** [comment]
The signed distance field text is using fwidth() which is not supported by standard GLES ES 1.0. In order to use it, the `bin/CoreData/Shaders/GLsL/Text.glsl` has to be modified to enable GL_OES_standard_derivatives at the beginning of the file:
```
#ifdef GL_ES
#extension GL_OES_standard_derivatives : enable
#endif
``` 
I tested and it worked with the workaround above. Seems like we need to inform Urho3D authors to keep this in mind.

**Comment by elix22** [comment]
I verified also , it works .
Would you like to inform the Urho3D Maintainers about this issue (maybe submit a P.R to Urho3D main) ?
You will be more then welcome in the Urho3D community with your current contribution.

**Comment by elix22** [comment]
For now I made a fix on the angle-metal-backend branch .
https://github.com/elix22/Urho3D/commit/708d775b4deaea101cf8fc606f415d885c6653b1
I will P.R. this fix to Urho3D upstream during the weekend

**Comment by kakashidinho** [comment]
Thanks.
I would like to inform them also. But seems like their priority is not OpenGL ES. Last time I notify them about npot textures have limited support in GLES 2 by default also.
Besides, right now, i'm too focusing on MetalANGLE. Currently using your urho3d as test beds for some cases.

**Comment by elix22** [comment]
Sure , no problem , focus on your stuff.
In the coming weeks I plan to rebase the branch on the latest Urho3D master and submit a P.R .

**Pull request merged**
