### PR TITLE
Removed unneeded ANGLE files to speedup compilation. Also updated MetalANGLE

### PR DESCRIPTION
**Pull request by kakashidinho**
Anw, what did change between this branch and angle-metal-backend branch? Seems like the shadow quality has become worse and high dpi is not working correctly.

When high dpi is enabled, SDL set window's layer scale factor to 2. It makes metal layer created a framebuffer with doubled size. The problem is that the Urho3D OGLGraphics layer still think the the framebuffer's resolution is the same, hence the final scene is only rendered to 1/4 of the screen.

### CODE REVIEW

**Comment by kakashidinho** [comment]
FYI, the updated MetalANGLE has some optimizations for dynamic buffer update. I think it should be useful for Urho3D.
Recently these was an interesting event, there was a user reported to me that he is using MetalANGLE for his game. And his game is using irrlicht (a quite old engine). So I forked irrlicht, integrating MetalANGLE into it and noticed irrlicht is updating buffer in a way that I didn't expect. It was not efficient, So these couple of days I have been trying to optimize that part inside MetalANGLE.

**Comment by elix22** [comment]
Thanks for that.
I don’t have much free time right now
I will work on that during the next weekend.
Yes there is an old issue with high dpi that needs some fixing , I will try to fix it

**Comment by elix22** [comment]
I disabled high dpi for now so it the same now as it was in angle-metal-backend branch .
On which device did you reproduce this issue ?

**Comment by kakashidinho** [comment]
I used my macbook connected to an external monitor. That monitor doesn’t even have retina

**Pull request merged**
