### PR TITLE
GLES3 experiments

### PR DESCRIPTION
**Pull request by kakashidinho**
This is experimental GLES 3 support in MetalANGLE. URHO3D_GLES3 is turned on by default. Passing `-DURHO3D_GLES3=FALSE` to cmake will disable it and turn on GLES 2 mode.

- With GLES 3 support, PBR materials sample is working fine now.
- GLES3 shader also has better built-in shadow sampler quality. Especially far away objects using low resolution shadow map will have better shadows compare to GLES 2 mode.

I don't have many iOS devices to test, but it's possible the performance could be slower. Not because GLES 3 mode is slower than GLES 2, but because Urho3D auto switchs to heavier rendering techniques if it detected GLES 3 is supported, for example, deferred rendering will be turned on, and it is slower than forward rendering on mobile platforms.

### CODE REVIEW

**Comment by elix22** [comment]
Thanks for this .
There is an issue with this branch 
Check "56_MaterialEffects" , some models are missing , specifically the mushrooms are missing.

You can compare this sample  with GLES2 enabled (-DURHO3D_GLES3=FALSE).

**Comment by elix22** [comment]
I merged it but I did set the default value of URHO3D_GLES3=FALSE

**Comment by elix22** [comment]
I fixed some Android compilation errors

**Comment by kakashidinho** [comment]
Regarding "56_MaterialEffects", it is a minor bug. "texture2D" has been renamed to "texture" in GLES3, Urho3d work around this by "#define texture2D texture". However, this define is only enabled in fragment shader, hence vertex shader compilation in "56_MaterialEffects" returned errors.
I have a small fix here https://github.com/kakashidinho/Urho3D/commit/f73274df2bfb87771e8e1646abbc2842ecb33860. Since it is a small fix, not sure it is worth to have PR yet.

**Comment by elix22** [comment]
Thanks
I will merge your fix manually

**Pull request merged**
